---

AWSTemplateFormatVersion: '2010-09-09'
Description: Database Hosts and Alarms

Parameters:
  FoundationStackName:
    Description: Foundation Stack Name
    Type: String

  InstanceType:
    Type: String
    Default: db.t2.small
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge

  Environment:
    Description: Stack environment
    Type: String
    AllowedValues:
      - integration
      - staging
      - production

  DatabaseCluster:
    Type: String

  DatabaseSubnetGroup:
    Type: String

  Replication:
    Type: String

  EnhancedMonitoring:
    Type: String

Conditions:
  ShouldCreateReplica: !Equals [ !Ref Replication, true ]
  ShouldEnableEnhancedMonitoring: !Equals [ !Ref EnhancedMonitoring, true ]

Resources:
  DatabaseMonitoringRole:
    Condition: ShouldEnableEnhancedMonitoring
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 'rds.amazonaws.com'
            Action: 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service: 'monitoring.rds.amazonaws.com'
            Action: 'sts:AssumeRole'

  DatabasePrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: !Ref InstanceType
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      CopyTagsToSnapshot: true
      MonitoringInterval: !If [ ShouldEnableEnhancedMonitoring , 60, 0]
      MonitoringRoleArn: !If [ ShouldEnableEnhancedMonitoring, !Ref DatabaseMonitoringRole, !Ref "AWS::NoValue" ]

  DatabaseReplicaInstance:
    Type: AWS::RDS::DBInstance
    Condition: ShouldCreateReplica
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: !Ref InstanceType
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      CopyTagsToSnapshot: true
      MonitoringInterval: !If [ ShouldEnableEnhancedMonitoring , 60, 0]
      MonitoringRoleArn: !If [ ShouldEnableEnhancedMonitoring, !Ref DatabaseMonitoringRole, !Ref "AWS::NoValue" ]

  DatabasePrimaryCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Primary database CPU utilization is over 80%.
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabasePrimaryInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      InsufficientDataActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"

  DatabaseReplicaCPUAlarm:
    Condition: ShouldCreateReplica
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Replica database CPU utilization is over 80%.
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabaseReplicaInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      InsufficientDataActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"

  DatabasePrimaryMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Primary database freeable memory is under 700MB.
      Namespace: AWS/RDS
      MetricName: FreeableMemory
      Unit: Bytes
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 200000000
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabasePrimaryInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      InsufficientDataActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"

  DatabaseReplicaMemoryAlarm:
    Condition: ShouldCreateReplica
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Replica database freeable memory is under 700MB.
      Namespace: AWS/RDS
      MetricName: FreeableMemory
      Unit: Bytes
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 200000000
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabaseReplicaInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      InsufficientDataActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"

  DatabasePrimaryReplicationAlarm:
    Condition: ShouldCreateReplica
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database replication latency is over 200ms.
      Namespace: AWS/RDS
      MetricName: AuroraReplicaLag
      Unit: Milliseconds
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 200
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabaseReplicaInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"

  DatabaseReplicaReplicationAlarm:
    Condition: ShouldCreateReplica
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database replication latency is over 200ms.
      Namespace: AWS/RDS
      MetricName: AuroraReplicaLag
      Unit: Milliseconds
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 200
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DatabaseReplicaInstance
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
