---

Description: ECS Cluster
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ComputeBucket:
    Description: Compute S3 Bucket
    Type: String

  Environment:
    Description: Stack environment
    Type: String

  FoundationStackName:
    Description: Foundation stack name upon which this cluster is installed.
    Type: String

  ClusterMaxSize:
    Type: Number
    Default: 4

  InstanceType:
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge

  SshKeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-hosts
      SecurityGroupIngress:
        - SourceSecurityGroupId:
            Fn::ImportValue: !Sub "${FoundationStackName}--ALB--SG"
          IpProtocol: -1
      VpcId:
        Fn::ImportValue: !Sub "${FoundationStackName}--VpcId"

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-ECSCluster

  EcsEc2Hosts:
    DependsOn:
      - Cluster
      - SecurityGroup
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
        FoundationStackName: !Ref FoundationStackName
        ClusterName: !Sub ${AWS::StackName}-ECSCluster
        SecurityGroup: !GetAtt SecurityGroup.GroupId
        ClusterMaxSize: !Ref ClusterMaxSize
        InstanceType: !Ref InstanceType
        SshKeyName: !Ref SshKeyName
      TemplateURL: !Sub https://s3.amazonaws.com/${ComputeBucket}/templates/ec2-hosts.yaml
      TimeoutInMinutes: 60

Outputs:
  ClusterName:
    Export:
      Name: !Sub "${AWS::StackName}--Cluster"
    Value: !Ref Cluster
  AppSecurityGroup:
    Export:
      Name: !Sub "${AWS::StackName}--AppSecurityGroup"
    Value: !Ref SecurityGroup
